version: "3"

networks:
  web:
    external: true
  # internal:
  #   external: false

services:
  httpd:
    image: httpd:alpine     # docker image dapat dicari pada hub.docker.io
    container_name: httpd   # Nama container
    restart: always         
    labels:
      - traefik.http.routers.httpd.rule=Host(`ivan.click`, `www.ivan.click`)  # domain tujuan
      - traefik.http.routers.httpd.tls=true
      - traefik.http.routers.httpd.tls.certresolver=lets-encrypt
      - traefik.port=80
    # volumes:
    #   - ../../public/:/usr/local/apache2/htdocs
    networks:
      - web
      # - internal